version: '2'
services:
    postgres:
        image: postgres:12.1
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: myuser
            POSTGRES_PASSWORD: myuserpassword
            POSTGRES_DB: mydb
        volumes:
            - ./postgresql/data:/var/lib/postgresql/data
